### ISSUE TITLE
Offer to display first 1000 rows

### ISSUE THREAD

**Issue by apnewberry** [dbcli/pgcli#1018]
> The result set has more than 1000 rows.
> Do you want to continue? [y/N]:

When I say `N`, I have to redo the query with a `LIMIT` clause. This can be annoying to wait when the query took a while. Instead of just `[y/N]` I'd like an option to display the first 1000 rows.

**Comment by j-bennet** [comment]
I think we want to do something like this:

* check and see if the query has LIMIT clause.
* if yes, do not change anything.
* if no, always limit to `row_limit = 1000` (https://github.com/dbcli/pgcli/blob/30c788917bf083aae6c4331ee102f8785c69432a/pgcli/pgclirc#L113), without any questions.
* change `row_limit` setting so that "0" means "do not limit".

**Comment by j-bennet** [comment]
Fixed in v2.2.0.

**Comment by glw** [comment]
on version 2.2.0 Im getting:

(pgcli) [user@user]$ pgcli --row-limit 0
could not connect to server: No such file or directory
	Is the server running locally and accepting
	connections on Unix domain socket "/var/run/postgresql/.s.PGSQL.5432"?

(pgcli) [user@user]$ pgcli --row-limit=0
could not connect to server: No such file or directory
	Is the server running locally and accepting
	connections on Unix domain socket "/var/run/postgresql/.s.PGSQL.5432"?

(pgcli) [user@user]$ pgcli --row-limit '0'
could not connect to server: No such file or directory
	Is the server running locally and accepting
	connections on Unix domain socket "/var/run/postgresql/.s.PGSQL.5432"?

So it appears to not recognize the configuration change and thinks im trying to connect to a db.

Also looked into config file at ~/.config/pgcli/config and no row-limit was listed in the file.
