### ISSUE TITLE
FATAL:  password authentication failed for user "postgres" when using non-default password

### ISSUE THREAD

**Issue by evenfrost** [dbcli/pgcli#1020]
## Description
When trying to connect to Postgres with standard `postgres` user which has non-default (not `postgres`) password, error is thrown:
```bash
FATAL:  password authentication failed for user "postgres"
```

Command I use:
```bash
pgcli --host localhost --port 5431 --dbname metabot --username postgres
```

`--password` argument does nothing (password prompt isn't shown either). Similar `psql` command (`psql --host localhost --port 5431 --dbname metabot --username postgres`) works without issues and shows password prompt. Installed `pgcli` via `pip` (v2.0.2). When installing with `sudo apt install pgcli`, it installs v1.6.0, and this version works well (shows password prompt and logs in after inputting the password). Tried to dump `pgcli` with config folder and reinstall but nothing changes.

## Your environment
Ubuntu 18.04, pgcli v2.0.2

`pip freeze` output:

```bash
asn1crypto==0.24.0
audioread==2.1.5
backports.csv==1.0.6
beautifulsoup4==4.6.0
certifi==2018.1.18
chardet==3.0.4
cli-helpers==1.1.0
Click==7.0
colorama==0.3.7
configobj==5.0.6
cryptography==2.1.4
decorator==4.1.2
enum34==1.1.6
html5lib==0.999999999
humanize==0.5.1
idna==2.6
ipaddress==1.0.17
keyring==10.6.0
keyrings.alt==3.0
lxml==4.2.1
mutagen==1.38
mysqlclient==1.3.10
numpy==1.13.3
pathlib2==2.3.0
pgspecial==1.11.5
pick-colour-picker==1.0
prompt-toolkit==2.0.9
psutil==5.4.2
psycopg2==2.7.7
puddletag==1.2.0
pyacoustid==1.1.2
pycairo==1.16.2
pycrypto==2.6.1
Pygments==2.3.1
pygobject==3.26.1
pymad==0.10
pyOpenSSL==17.5.0
pyparsing==2.2.0
python-apt==1.6.3+ubuntu1
python-Levenshtein==0.12.0
pyxdg==0.25
requests==2.18.4
scandir==1.7
scour==0.36
SecretStorage==2.3.1
setproctitle==1.1.10
six==1.12.0
sqlparse==0.2.4
tabulate==0.8.3
terminaltables==3.1.0
urllib3==1.22
wcwidth==0.1.7
webencodings==0.5
wxPython==3.0.2.0
wxPython-common==3.0.2.0
```

**Comment by j-bennet** [comment]
I can't reproduce the problem. I am on a Mac, but also tried with a docker container based on a `python:3.5.6-stretch` image. A couple more questions:

* which python version are you using?
* are you really connecting on a non-standard port (`--port 5431`), or is that a typo?

**Comment by quezak** [comment]
I'm having the same issue: `pgcli` doesn't even prompt for password, even with the `-W` switch enabled (what does the switch do then?)

In my case I have two almost identical setups, one of which runs a test system with a default password. I'm tunneling the db connection from both via ssh, then try to connect to their databases:

```
(separate shell) ssh <real-machine> -L 5433:...:5432
(separate shell) ssh <test-machine> -L 5434:...:5432

...>: pgcli -h localhost -U postgres -p 5433
FATAL:  password authentication failed for user "postgres"
FATAL:  password authentication failed for user "postgres"

...>: pgcli -h localhost -U postgres -p 5434
Server: PostgreSQL 9.4.21
Version: 2.0.0
Chat: https://gitter.im/dbcli/pgcli
Mail: https://groups.google.com/forum/#!forum/pgcli
Home: http://pgcli.com
postgres@localhost:postgres>                                
```

pgcli version: 2.0.0 (just updated to 2.0.2 -- no changes)
python 3.6.6
gentoo linux
is there any more info that would be helpful?

**Comment by j-bennet** [comment]
@quezak Things that may be helpful:

* `pip freeze | grep -P "(psycopg2|keyring|helpers|lick)"`
* what kind of auth you have configured in `pg_hba.conf`

@dbcli/pgcli-core Can you give me a hand with reproducing this?

**Comment by quezak** [comment]
```
...>: pip freeze | grep -P "(psycopg2|keyring|helpers|lick)"
cli-helpers==1.1.0
Click==7.0
cupshelpers==1.0
keyring==13.2.1
psycopg2==2.7.5
```

I'll update when I get info about the db.

**Comment by j-bennet** [comment]
@quezak Do you have any postgres env variables set (i.e. PGHOST, PGUSER, PGPASSWORD, etc)?

**Comment by j-bennet** [comment]
@quezak I have a theory. It is possible, if you are using keyring, that default password for `postgres` was previously stored there. Now you have changed it, the stored password is not correct anymore, but `pgcli` is not asking you for password because it only asks if you did not provide one, and you provided one via keyring:

https://github.com/dbcli/pgcli/blob/1c66dece59d4595eee3fb33d2609e2e288a28ff4/pgcli/main.py#L459-L463

Here is how you can confirm the theory:

```
$ python
import keyring
keyring.get_password('pgcli', 'postgres@localhost')
```

Do you see an incorrect stored password?

**Comment by quezak** [comment]
@j-bennet your guess was right -- the keyring was enabled and had the default password stored. Changing it doesn't make sense, since in my case I'm connecting to different databases using the same `postgres@localhost` login (using tunneled connections), so I've disabled the keyring for now. Thanks for the help!

Solution proposal: maybe pgcli should prompt for password anyway when the keyring password fails?

I also have two questions left:
 * what's the intended behavior of the `-W` switch, described as `Force password prompt`? Especially when combined with the keyring. Right now it looks like it doesn't do anything in this configuration, which seems weird -- I'd expect it to either override the keyring and prompt for password, or print a message that keyring is enabled and that's why it doesn't prompt despite the switch.
 * this is more of a subjective matter -- should the keyring be enabled by default? I've never edited the pgcli config, so I had no idea that `pgcli` uses remembers passwords by default (I just thought it doesn't need to prompt for the default `postgres` password). This looks like a security concern for me -- I'm sometimes entering sensitive production passwords there, and now I feel uneasy that they could be stored anywhere. Note that I'm not against (secure) password storage here, just against storing password without the user explicitly knowing about it :)

**Comment by j-bennet** [comment]
> Solution proposal: maybe pgcli should prompt for password anyway when the keyring password fails?

Yes, absolutely, that's the right way to handle it. It should prompt for password when existing password fails, and it should update stored password with the new one on successful connection. If you're willing to submit a PR, I'll happily merge that, otherwise I'll do the fix.

> what's the intended behavior of the -W switch, described as `Force password prompt`?

It should force password prompt in case if password is not provided. In context of keyring, this behavior gets a little weird, because even when you, the user, did not provide a password, `keyring` did behind the scenes, so `-W` gets ignored. I'm starting to think that maybe `-W` should force password no matter what. But I'm not quite sure about that yet.

> this is more of a subjective matter -- should the keyring be enabled by default?

Generally, when we add a new feature (and `keyring`, when works correctly, is a user-friendly feature), we want it enabled. Discoverability is important - what's the point of a new feature if it is buried in config file and nobody will ever dig through and think about enabling it.

By default, `keyring` flag in pgcli config is set to `True`, but `keyring` package is listed as an optional requirement, so first time pgcli runs with this flag == True, it will tell the user: "if you want to use keyring to store passwords, you need to install the keyring package". Passwords are only going to be stored if both requirements are met:

* keyring is enabled in config.
* keyring package is installed.

That lets us know that user made the conscious choice of using `keyring`. Except in your case, `pgcli` is installed system-wide and not in a venv, so I think `keyring` was installed by some other package and not `pgcli`. That makes it a bit less conscious! But I still think that we should stick to our discoverability principle, because it has more pros than cons, once all the wrinkles of the new feature are ironed out.

**Comment by quezak** [comment]
Thanks for the explanation! Discoverability is indeed an important thing. Maybe pgcli could ask if the user wants to store the passwords on the first login? (e.g. ask if the `use keyring` config is not set, and then set the config according to the answer). Up to you what will you want to do with it, I just wanted to raise the issue :)

**Comment by j-bennet** [comment]
Yes, that's something to think about. Thank you for the suggestion!

**Comment by peterlandry** [comment]
I've hit this bug as well, and turning off keyring in pgcli config doesn't help me. I've installed `pgcli` in a `3.12.1` virtualenv on ubuntu, and get a password authentication error when connecting with `pgcli`. The exact same options and password succeed when using `psql` directly. Is there anything else going on that could cause this?
