### ISSUE TITLE
Cant connect to pgcli on windows 10

### ISSUE THREAD

**Issue by ArunVenkata** [dbcli/pgcli#1050]
I've installed pgcli successfully and when I run it on windows 10,

I run using: 

pgcli -h localhost -p 5000 -U arun testdb

It says the following:

could not send data to server: Socket is not connected (0x00002749/10057)
could not send SSL negotiation packet: Socket is not connected (0x00002749/10057)

**Comment by j-bennet** [comment]
So you're using SSL with Postgres.
What version of openssl do you have installed?
Can you post the output of your `pip freeze` command?

The closest I could find to your issue is this:

https://www.postgresql.org/message-id/DM5PR17MB149904D416723D5B77604CAADAB60%40DM5PR17MB1499.namprd17.prod.outlook.com

and there seems to be no response.

@meeuw I'd appreciate if you can take a look.

**Comment by eDeepake** [comment]
I have the same issue as well on Windows 10. Here's the output of 'pip freeze' command.  
The PGAdmin4 is working.

pip freeze
cli-helpers==2.0.1
click==7.1.2
configobj==5.0.6
humanize==2.4.0
pgcli==3.0.0
pgspecial==1.11.10
prompt-toolkit==3.0.5
psycopg2==2.8.5
Pygments==2.6.1
setproctitle==1.1.10
six==1.15.0
sqlparse==0.3.1
tabulate==0.8.7
terminaltables==3.1.0
wcwidth==0.2.4

**Comment by fraoustin** [comment]
Hi

you can test the connection, with a pgcli docker

```
docker run --rm -it dbcliorg/pgcli -h <YourIP> -p 5432 -U postgres -W 
```

<YourIp> is not localhost or 127.0.0.1
