### ISSUE TITLE
Autocomplete on Enter

### ISSUE THREAD

**Issue by agzam** [dbcli/pgcli#1087]
Is there a way to make it, so pressing Enter would just pick up very first suggestion and use it? It's really annoying to have to press `→` and then Enter.

**Comment by j-bennet** [comment]
This feature might end up doing more harm than good. In multiline mode, `enter` to complete the first choice would be annoying and inconvenient. In case of a destructive query (`DROP` or `DELETE`, it would make it too easy to select the wrong suggestion. I don't think we want to do this.

**Comment by agzam** [comment]
Can't we have a flag in the settings that's ignored in multiline mode?

**Comment by j-bennet** [comment]
We try very hard not to add extra config settings. Also, in addition to multiline mode, this would require special handling for destructive queries, and I'm sure there are other use cases I'm not thinking about right now where accidental first choice would be bad. There's not enough benefit to justify the potential danger.

**Comment by telmotrooper** [comment]
Sorry to revive this old thread, but would it be that bad if, with the option manually set by the user, pressing ENTER would just type in the first suggestion but not actually execute it?

That would allow me to work with `pgcli` similarly to how I work with `DBeaver`, right now when I switch between them it feels really confusing.

**Comment by j-bennet** [comment]
@telmotrooper so basically you'd like Enter to work the same as Tab key?

**Comment by telmotrooper** [comment]
Optionally, yes. 🙂️

**Comment by j-bennet** [comment]
@telmotrooper I have a branch with the change you requested. Can you give it a try and see if it works as you expect? Here is the command to install from branch:

`pip install git+https://github.com/dbcli/pgcli.git@j-bennet/enter-accept-first`

**Comment by j-bennet** [comment]
@telmotrooper Did you have the cnagce to try pgcli from the branch?

**Comment by telmotrooper** [comment]
@j-bennet Hey, just tried it out in the branch. That's exactly what I had in mind! Thank you for implementing it.

It feels way more natural to switch between DBeaver and pgcli this way. I'll be glad if you guys decide to implement it as a toggleable feature in the main branch, for now I'll be using the feature branch. 😁️

**Comment by j-bennet** [comment]
@telmotrooper Try reinstalling from branch - I made a change so that it should work in multiline mode as well. It would be great if you can run this branch for a while and report back whether or not you see any unexpected / weird keybinding behaviors.

**Comment by telmotrooper** [comment]
@j-bennet Will do. Thanks!

**Comment by j-bennet** [comment]
@telmotrooper did the change work for you?

**Comment by telmotrooper** [comment]
Actually I'm on vacation from work and haven't been using pgcli much, I had seem some weird behavior regarding multiline mode but I gotta take the time to write the instructions to reproduce. Sorry for taking so long!

By the way, @j-bennet, where do contributors usually discuss development? I wrote a message on Gitter early this month but haven't received any answers.

**Comment by j-bennet** [comment]
@telmotrooper I think communicating via Github issues is best. Most of us (maintainers) don't often check gitter.

**Comment by telmotrooper** [comment]
@j-bennet Hey, been trying to test it this week. I had installed pgcli in development mode before (so when you edit the code it reflects your current installation) here in the company computer (which I was using at home because of the COVID-19 isolation).

Installing your branch with `pip install git+https://github.com/dbcli/pgcli.git@j-bennet/enter-accept-first` seems not to change anything (but I do remember it worked before!). I tried removing all settings related to pgcli but I can't get it to work. Do you have any suggestion? Sorry for bothering you with that.

**Comment by j-bennet** [comment]
@telmotrooper hmm. I just tried this branch again (rebased on top of master) and it still works for me. Are you able to install it into a new virtualenv?

```
python -m venv /path/to/my-new-venv
source /path/to/my-new-venv/bin/activate
pip install git+https://github.com/dbcli/pgcli.git@j-bennet/enter-accept-first
```

**Comment by telmotrooper** [comment]
Okay, sorry for the long delay. Had some time to test this at home today.

Mostly it seems to work nice both in single and multi line mode, but I noticed that if I type `*` and press ENTER, it selects the completion alternative and ENTER again makes it go away.

I recorded a short video:
![Short video showing issue](https://media.giphy.com/media/L3j8t3gOYVsYW93vOX/giphy.gif)
This does not seem to happen with other completions.

I also noticed that even if a previous command is suggested, auto complete will still complete to the first entry in the list:
![Short video showing this other issue](https://media.giphy.com/media/Za2CED4gN2sPeURKPf/giphy.gif)
That, even if a bit counter intuitive, isn't really an issue since pressing Right Arrow will still get to the suggestion.

I remember back when I first tried I had some issue with multi line, but I can't seem to reproduce it now. Mostly I think the current state of the branch is already pretty useful for someone coming from DBeaver, we would just need a setting somewhere to change to this behavior.

By the way, thank you for implementing it. 🙂️

**Comment by j-bennet** [comment]
@telmotrooper I looked into completion logic, and I don't think it's a bug. It's the way we handle asterisk to expand it into table columns. When you press ENTER on asterisk, it is expanded to list of table columns. Second ENTER will accept and close the completion drop-down. Here are two possible use cases:

1. User types `select *`. Pgcli looks within query context and does not find any tables. This is why, when user press ENTER, even though `*` is present in the list of completions, pgcli suggests nothing (empty text). Second ENTER will close completion drop-down and "accept" the empty suggestion.

2. User types `select from table_name`, and then navigates cursor after `select` and presses SPACE. At this point, pgcli finds `table_name` within query context. If user presses ENTER here, then "*" (the first completion in the list) will be expanded to `col1, col2`. Second ENTER will insert that into query, and query will become `select col1, col2 from table_name`.

I think this behavior makes sense. What do you think?
