### ISSUE TITLE
Overload up/down arrow to match partially typed in query from history.

### ISSUE THREAD

**Issue by amjith** [dbcli/pgcli#113]
Right now, up/down arrow will navigate the history. 

But if someone enters a partial query in the REPL (such as 'SEL') and hit up arrow then it should only cycle through the entries that start with 'SEL' such as 'SELECT \* FROM abc'. 

This is probably a prompt_toolkit addition, but adding it here to keep track. 

/cc @jonathanslenders your thought on this would be appreciated.

**Comment by jonathanslenders** [comment]
True. There is an issue for this: https://github.com/jonathanslenders/python-prompt-toolkit/issues/36

It's not an easy one. I'm not sure whether this can be handled correctly in a multiline context. Also not the biggest priority for me, but certainly on the to do list.

**Comment by amjith** [comment]
I'll take a stab when I get some time. I think it's a useful feature, but you're right about having complications in multi-line mode.

**Comment by jonathanslenders** [comment]
Hi @amjith @shanusmagnus @Vayn @ianozsvald @j-bennet,
``prompt_toolkit`` does now support this kind of history substring matching when pressing arrow-up.

Right now, it works by passing ``Always()`` to ``Buffer.enable_history_search``:
https://github.com/jonathanslenders/python-prompt-toolkit/blob/f9c54569d98603c98a6f34134c287399f70ed283/prompt_toolkit/buffer.py#L157

Please tell me whether I should rename ``enable_history_search`` by ``enable_history_substring_matching``! I'd like to use the correct terminology. I'm not sure how readline calls this option exactly.

There is one issue however. When ``complete_while_typing`` is enabled, and there are completions, then the up and down arrows traverse all these completions rather than going through the history.
So, what I did for ``ptpython`` (master branch -- not on Pypi yet), I disabled ``complete_while_typing`` as soon as somebody enable ``history_search`` from the menu.

Suggestions are very welcome.

Jonathan

**Comment by amjith** [comment]
@jonathanslenders I believe it is called 'history-search-backward()' in [readline](http://www.gnu.org/software/bash/manual/bashref.html#Commands-For-History). It's not all that clear from the name. 

I have a suggestion for the up/down arrow traversing the suggestion menu. When this option is enabled you can still have complete_while_typing enabled, but then disable the up/down arrow to choose the items in the menu. But instead use tab/shift-tab for selecting menu items. Because I hardly ever use the arrow key to select an item from the menu, I always use tab keys.

**Comment by j-bennet** [comment]
This has been in `python-prompt-toolkit` for a long time now, but between partial history match and autocomplete-as-you-type, autocomplete is the more useful one, and we can't have both. I'm closing the issue.
