### ISSUE TITLE
pgcli is too slow to connect to the postgresql

### ISSUE THREAD

**Issue by weni09** [dbcli/pgcli#1272]
## Description
pgcli is too slow to connect to the postgresql,while native psql client is not.

ps: Mycli is just as fast as the native mysql client
## Your environment
OS:Ubuntu 20.4 x64
postgresql:12.7
pgcli:3.1.0
##my command
```shell
pgcli -hlocalhost -Upostgres
```

**Comment by dbaty** [comment]
I cannot reproduce any slowness. At least, pgcli does not appear obviously slower than psql.

Do you confirm this issue with the latest version? Can you provide more details:
- What is too slow (the startup/connection to the server, sending the queries, getting/displaying query results, etc.)?
- How slow is it (numbers would surely help, as well as a comparison with psql)?
- Do you have server logs that show that the slowness is on pgcli side and not due to the server (PostgreSQL) configuration?

**Comment by dbaty** [comment]
No news nor details from the reporter, and no other similar reports. I am closing this.
