### ISSUE TITLE
Add alert bell/notification once query is complete

### ISSUE THREAD

**Issue by AetherUnbound** [dbcli/pgcli#1297]
## Description

Frequently I will issue a command to pgcli in one terminal that will take some time to execute. I usually navigate away from the window after I start the command to jump into other work. It's then on me to be checking every x-minutes to see if the command has completed. Do you think it would be possible/reasonable to add an option for emitting a terminal bell sound/notification once a command has finished executing? That way I might know to check back in and continue whatever work I was doing with that database.

## Your environment

- [X] Please provide your OS and version information: **Linux: Xubuntu 18.04**
- [X] Please provide your CLI version: 3.2.0

## P.S.
Thanks for the wonderful tool you all put work into to support!

**Comment by shabble** [comment]
You can potentially do something along these lines already:

```
select 'Some result', pg_sleep(2); /* example slow query */
\!` bash -c "for x in {1..5}; do tput bel; sleep 0.1; done" /* spams 5 terminal-bells to alert you */
```

It should be possible to use `\!` to invoke `notify-send` or some other desktop notify client to alert you with a popup, if you're running direct on the host, or forward d-bus somehow (untested since I'm currently using pgcli inside docker).

**Comment by AetherUnbound** [comment]
That's good to know! I didn't realize I could shell out from `pgcli`.
