### ISSUE TITLE
Crash: image not found

### ISSUE THREAD

**Issue by timscott** [dbcli/pgcli#132]
I get this error:

```
> pgcli
Traceback (most recent call last):
  File "/usr/local/bin/pgcli", line 9, in <module>
    load_entry_point('pgcli==0.13.0', 'console_scripts', 'pgcli')()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources.py", line 357, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources.py", line 2394, in load_entry_point
    return ep.load()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources.py", line 2108, in load
    entry = __import__(self.module_name, globals(),globals(), ['__name__'])
  File "/Library/Python/2.7/site-packages/pgcli/main.py", line 24, in <module>
    from .pgexecute import PGExecute
  File "/Library/Python/2.7/site-packages/pgcli/pgexecute.py", line 2, in <module>
    import psycopg2
  File "/Library/Python/2.7/site-packages/psycopg2/__init__.py", line 50, in <module>
    from psycopg2._psycopg import BINARY, NUMBER, STRING, DATETIME, ROWID
ImportError: dlopen(/Library/Python/2.7/site-packages/psycopg2/_psycopg.so, 2): Library not loaded: @loader_path/../lib/libssl.1.0.0.dylib
  Referenced from: /Library/Python/2.7/site-packages/psycopg2/_psycopg.so
  Reason: image not found
```

**Comment by amjith** [comment]
Sorry about the crash. 

It looks like psycopg2 is having trouble loading. 

Do you have postgres installed on the machine you're trying to run this? 

Can you launch the python interpreter and try importing psycopg2? 

```
$ python
>>> import psycopg2
```

If that doesn't succeed then you probably don't have psycopg2 installed correctly. I'd recommend installing postgres first and then trying a `pip install psycopg2`. 

Alternatively, if you're okay with a slightly older version of pgcli you can install it via brew. 

```
brew install pgcli
```

**Comment by amjith** [comment]
It looks like the libpq installed on your OS X machine has some linking issues. This is related to psycopg2 installation which is required by pgcli to talk to Postgres database. There are a few possible workarounds covered in the articles below:

http://joshuakehn.com/2013/10/13/Postgresapp-and-psycopg2-on-OS-X.html
http://stackoverflow.com/a/21357519/8825

Were you able to get this resolved?

**Comment by amjith** [comment]
I'm closing this issue as I haven't heard back in a while. If you have more trouble feel free to reopen.

**Comment by szeitlin** [comment]
I'm having this problem, in my case it's definitely related to libssl.1.0.0.dylib, but following these directions just made my problem worse since now my /usr/lib version of libssl is broken. 

I don't understand what's happening b/c anaconda has its own pointer to openssl, and that seemed to work fine for other things, but psycopg2 doesn't seem to be able to find it even though it's right there in the same virtualenv. Now I have to figure out how to fix what I just broke. :-1:

**Comment by amjith** [comment]
@szeitlin Sorry about the crash. Can you tell me what OS you're using and how you're installing pgcli? 

Do you have postgres on the machine? What is the error message you're getting? 

If you're on OS X, can you try installing it via brew?

**Comment by szeitlin** [comment]
well, the good news is, pgcli installed just fine and python seems to be able to find psycopg2 just fine! 

unfortunately, django is confused (which is why I wanted to install postgres in the first place). 

I've run into problems with this before - I think anaconda and brew don't play together quite as well as they should, at least for some things (and libssl seems to be one of those).
