### ISSUE TITLE
Does pgcli integrate with .psqlrc?

### ISSUE THREAD

**Issue by jaytaylor** [dbcli/pgcli#20]
Does pgcli integrate with .psqlrc?  If not, do you have any plans to add support for it?

Here is an example of my .psqlrc file: https://gist.github.com/jaytaylor/e5aa89c8f3aaab3f576f

**Comment by jackmaney** [comment]
:+1:

**Comment by amjith** [comment]
Right now it doesn't have support for .psqlrc. But that's not a bad idea. 

That said, I looked at your .psqlrc, man it's a beast. That'll take some time to get done. 

I should probably mention that it does create a .pgclirc file in your home folder.

**Comment by njhazelh** [comment]
:+1:

**Comment by yuki777** [comment]
:+1:

**Comment by fernandomora** [comment]
:+1:

**Comment by abloch** [comment]
:+1:

**Comment by slava-pagerduty** [comment]
please add the support for .psqlrc

**Comment by okbob** [comment]
I think so integration .psqlrc is bad idea - it create strong dependency in design - and probably nobodu expect compatibility between psql and pgcli. But the idea is correct, and some like .pgclirc should be implemented. Somebody can use symlink to .psqlrc

**Comment by amjith** [comment]
@okbob Thanks for articulating my concerns. 

We will never be able to catch up to the features supported by `psql`. Rather than playing catch up with psql, I'd rather stand apart as an alternative that has overlapping features. 

There is a pgclirc which is located under ~/.config/pgcli/config and it is well-documented about the things one can tweak.

I'm closing this as "Won't Fix".
