### ISSUE TITLE
Implement (\i) and (\cd) commands in pgcli

### ISSUE THREAD

**Issue by eolo999** [dbcli/pgcli#205]
When I try to change folder with \cd the parser thinks I am trying to connect to another database:

    my_database> \cd whatever
    FATAL:  database "whatever" does not exist

**Comment by amjith** [comment]
LOL!

Did you try creating a folder called "whatever"? Just kidding. 

Yes `\cd` is not an available command. Right now any command that starts with a `\c` is treated as a change DB, which is wrong. The fix for that is already in the `master` branch, waiting to be released.

But I'm more interested in the use case that comes after it. 

What exactly do you do after you change the directory? Because pgcli does not have support for interacting with things that are in the current folder. So if you have a use case in mind, I'd be interested to hear it.

**Comment by eolo999** [comment]
I have a lot of pl/pgsql functions which I often reload from files with the  __\i__ command.

**Comment by amjith** [comment]
Adding `\i` is the real goal then. 

I'm going to change the title of this issue to implementing `\i` since that is going to be much harder than implementing `\cd`.

**Comment by eolo999** [comment]
Thanks a lot.

**Comment by sixpi** [comment]
Going along with `\i` support, `\o` support would be awesome.

**Comment by amjith** [comment]
Support for `\i` is now available in the latest release of pgcli.

**Comment by zoner14** [comment]
+1 for \i support
