### ISSUE TITLE
SELECT … INTO suggests existing tables

### ISSUE THREAD

**Issue by drocco007** [dbcli/pgcli#212]
`SELECT … INTO ` suggests the currently-available set of tables, but this is misleading as the `SELECT … INTO` command needs the name of a *new*, nonexistent table that will be created and populated with the output of the `SELECT`

![select_into_tables](https://cloud.githubusercontent.com/assets/1424858/7217282/dea82ce2-e5ed-11e4-97e3-34e65ab73631.png)

I'm actually not sure what the best user experience behavior is here, so I'd love to discuss our options.

**Comment by darikg** [comment]
`create table` does the same thing. imo it actually kinda makes sense -- I can imagine wanting to make a new table with the same name as an existing one, but with an extra suffix.

**Comment by amjith** [comment]
I'm actually with @darikg on this one for a couple of reasons. 

1. As Darik mentioned sometimes I tend to create a table that happens to a copy of an existing table in which case it has a suffix added to the existing table name. 

2. It serves as a reminder of what tables are already available. This is mostly for playing around, but I create tables called or 'test' or 'sample' to test a specific bug and it's good to see that it already exists so I can name it something different rather than get an error.

**Comment by drocco007** [comment]
oh, I agree, and I wasn't suggesting we remove the suggestions. Mostly I was just musing about this from a signaling perspective, trying to see if we could think of a way to convey to users that these are the table names that you *can't* use, as opposed to the normal suggestion of ones that you can. But I haven't been able to think of a way that wouldn't be some combination of awkward, difficult, or confusing, so I think you folks are right that we should just leave this as it is.
