### ISSUE TITLE
Format of pasted query

### ISSUE THREAD

**Issue by kentor** [dbcli/pgcli#221]
When I paste a query with line breaks into pgcli, the lines are joined without a space.

for example:

```
select col
from table
```

becomes

`select colfrom table`

which is a syntax error

**Comment by amjith** [comment]
Actually in order to paste multi-line strings like the one in the example, you have to enable the multi-line mode (F3 key). 

If you notice the syntax error says 

```
misago> select colfrom table
column "col" does not exist
LINE 1: select col
```

Even though it printed it as `select colfrom table` what it actually did was it pasted `select col` and the newline after that was treated as <enter> and it sent the partial query to the server and then pasted the rest of the query into the buffer. 

But if you enable multiline-mode and then paste the same snippet, it will be pasted correctly and then you can end it with a semicolon and press enter to execute the query. 

Try it out and let me know if it works.

**Comment by kentor** [comment]
thanks that works :+1:

**Comment by iamrahulroy** [comment]
@amjith don't you think it should be default config for new users as the same setting is enabled by default for the offcial psql console.

**Comment by amjith** [comment]
@iamrahulroy That's debatable. Some of the default behaviors in psql are just terrible, so I'm ok deviating from what is considered default in psql. 

But this one is a subjective call and I'm not sure there is a good way to objectively say one is better than the other. I've chosen what I think is the most common use case, which is people type in queries in a single line and multi-line queries are rare. So I've optimized based on that use case. But if a user prefers to emulate psql there is a config option that allows them to do that. 

The philosophy behind pgcli is "Sane defaults out of the box".

**Comment by darikg** [comment]
I mentioned in #389 that it would be nice to detect newlines in pasted text, and auto-switch to multi-line mode. That'd be pretty sane imho.

**Comment by amjith** [comment]
That'd be a great addition @darikg.
