### ISSUE TITLE
Use the inet address when port is specified at launch

### ISSUE THREAD

**Issue by amjith** [dbcli/pgcli#229]
Related to #37. 

Reported by @SpotlightKid

> if you specify a port with the -p command-line option, but no host with the -h option, pgcli still tries to use a unix domain socket. Maybe it should assume an inet socket and localhost as the default hostname in that case, since specifying a port doesn't make sense with unix domain sockets.

**Comment by cbandy** [comment]
> since specifying a port doesn't make sense with unix domain sockets.

Not true. `port` is appended to the socket file name so that different instances of postgres can use the same socket directory without conflict.

From the docs for [`unix_socket_directories`](http://www.postgresql.org/docs/current/static/runtime-config-connection.html#GUC-UNIX-SOCKET-DIRECTORIES):

> In addition to the socket file itself, which is named `.s.PGSQL.nnnn` where `nnnn` is the server's port number, an ordinary file named `.s.PGSQL.nnnn.lock` will be created in each of the `unix_socket_directories` directories.

Here's what `psql` does on some Ubuntu with a `-p` command-line option but no host with the `-h` option:
```sh
$ psql -p 5010
psql: could not connect to server: No such file or directory
        Is the server running locally and accepting
        connections on Unix domain socket "/var/run/postgresql/.s.PGSQL.5010"?
```

**Comment by j-bennet** [comment]
What @cbandy said. :)
