### ISSUE TITLE
Pasting queries can be slow

### ISSUE THREAD

**Issue by NotSqrt** [dbcli/pgcli#238]
Hi,

I want to paste a query like 
```sql
explain SELECT "sentry_message"."id", "sentry_message"."group_id", "sentry_message"."message_id", "sentry_message"."project_id", "sentry_message"."logger", "sentry_message"."level", "sentry_message"."message", "sentry_message"."view", "sentry_message"."checksum", "sentry_message"."num_comments", "sentry_message"."platform", "sentry_message"."datetime", "sentry_message"."time_spent", "sentry_message"."server_name", "sentry_message"."site", "sentry_message"."data" FROM "sentry_message" WHERE ("sentry_message"."group_id" = 6530  AND NOT ("sentry_message"."id" = 5710758 ) AND "sentry_message"."datetime" <= '2015-05-18 16:23:24+00:00' ) ORDER BY "sentry_message"."datetime" DESC LIMIT 1;
```

But just pasting it and seeing it appear at the prompt can take 15 seconds, while using the history is instantaneous.
Does it try to run completion on every character ?

**Comment by amjith** [comment]
You're right it does take a while. 

I believe it's a limitation of `prompt_toolkit` and the datastructure used to consume the line. 

@jonathanslenders Is the slowness due to auto-completion triggering for each character press? Is it possible to disable auto-completion triggers in a special paste mode? Or detect the paste mode automatically by detecting how fast the characters are coming in?

**Comment by jonathanslenders** [comment]
Hi @NotSqrt and @amjith 

Yes, this is currently a limitation of prompt-toolkit, but I'm working on improving that. (It has nothing to do with autocompletion.)

The reason that this is slow, comes from that every single key press goes through two huge state machines. The first one is a vt100 parser which is rather fast. The second is the key binding processor. (Which has a rather large set of sequences of key bindings, all with enable/disable conditions attached to them.)

It became really noticeable during the development of pyvim. So, I hope to be able to do some bench marking and optimizing before the next release of prompt-toolkit.

Jonathan

**Comment by jonathanslenders** [comment]
So this is fixed in the following commits:

https://github.com/jonathanslenders/python-prompt-toolkit/commit/5a1aa22b7d88bfd4bbed6cb3dba833c3f7ead17f
and https://github.com/jonathanslenders/python-prompt-toolkit/commit/1d17122ecb858509c8d5f50505eeb53b417e5195

The first commit improves the speed of the state machine for the key bindings significantly. (We can have key bindings for any key, so also ASCII keys are also going through that state machine.) This patch made a huge difference.

The second commit also doubles the speed, by delaying executors until the main thread is idle. This was indeed the autocompletion taking resources. Not on every key press, but there was always one autocompletion thread running during the whole paste. We didn't need that.

Cheers,
Jonathan

**Comment by amjith** [comment]
I'll upgrade prompt_toolkit dependency as soon as it is released to pypi. 

Thanks a lot for the quick turn around Jonathan. :)

**Comment by amjith** [comment]
@NotSqrt The fix is now merged into master. You can install from master and try it out. 

```
pip install -U -e git+https://github.com/dbcli/pgcli.git#egg=pgcli
```

**Comment by NotSqrt** [comment]
Perfect ! Tested and good to go !

**Comment by amjith** [comment]
Awesome! Thank you for testing it.

I'll release a new rev to PyPI once we merge in a few pending PRs. Hopefully it'll go out this weekend.
