### ISSUE TITLE
Use PAGER if the output is to wide

### ISSUE THREAD

**Issue by Knorkebrot** [dbcli/pgcli#286]
That'd be nice :)

**Comment by amjith** [comment]
Can you elaborate? I'm not sure what you mean by READER.

**Comment by Knorkebrot** [comment]
Oh, I mean PAGER, sorry.

**Comment by amjith** [comment]
I already use the PAGER for output that doesn't fit in the screen. Wider output is a different issue and using a PAGER there doesn't really help.

**Comment by Knorkebrot** [comment]
Why would that be a different issue?

**Comment by amjith** [comment]
Can you jump on gitter? We can hash it out. 

https://gitter.im/dbcli/pgcli

**Comment by Knorkebrot** [comment]
I'm in a hurry, I'll join later.

**Comment by Knorkebrot** [comment]
For illustration: http://tmp.kbct.de/pager.gif

**Comment by amjith** [comment]
Thoughts from gitter chat: 

Easy solution is to add -S to the less_opts and that'll achieve the right results. 

Correct solution is to append to the existing LESS env var instead of replacing the current LESS env var with -SRXF.

Extra credits for providing a way for the user to set the pager options at run time (kinda like how mysql repl does). Using a 'pager' special command. 

Thank you @Knorkebrot for the illustration gif.

**Comment by amjith** [comment]
@Knorkebrot This is now implemented in master. You can try it out by installing pgcli directly from master, as follows: 

```
pip install -U https://github.com/dbcli/pgcli/archive/master.zip
```

You can change the pager at runtime using `\pager [command]`. Eg: `\pager less -S`.

**Comment by fernandomora** [comment]
Could it be possible to set default pager and options in .pgclirc using a line like  `pager = less -iMSx4FXRe` ?
Otherwise it is necessary to set preferred pager options each time pgcli is executed.

**Comment by amjith** [comment]
I can add the pager to the config file. 

In the mean time pgcli does honor the env var PAGER. So you can set your PAGER env var to `less -iMSx4FXRe` and it will be used by pgcli.

**Comment by Knorkebrot** [comment]
Works like a charm :)
