### ISSUE TITLE
Ctrl-C exits pgcli and introduces strange behavior in bash

### ISSUE THREAD

**Issue by mikekaminsky** [dbcli/pgcli#288]
Connecting to a remote DB and running `\d` lists relations as expected. Hitting Ctrl-C aborts pgcli and causes issues in bash on exit(can't see input, return doesn't jump to new line). Ctrl-C probably should not abort the whole program.

See this discussion about this behavior in the mysql command line client:
https://bugs.mysql.com/bug.php?id=66583

Found this behavior in pgcli Version: 0.17.0

**Comment by amjith** [comment]
The Ctrl-C aborts pgcli only if you're in the pager. If you're just in the regular pgcli prompt it doesn't abort when you Ctrl-C. 

This is due to a bug in one of the libraries I use called 'Click' for piping the output through a pager. 

I've fixed the bug in click and sent a PR which is already merged. https://github.com/mitsuhiko/click/pull/351

But I'm waiting for them to release a new version so I can bump up the dependency of Click. 

Sorry about the aborting behavior. You can recover from the terminal weirdness by typing 'reset' in the terminal.
