### ISSUE TITLE
Errors in later semicolon separated commands hide output from earlier commands

### ISSUE THREAD

**Issue by darikg** [dbcli/pgcli#335]
E.g.
```
test_db> select 1; select;
syntax error at end of input
LINE 1: select
```

The output from the first command should be printed before the error traceback in the second

**Comment by amjith** [comment]
Good catch. 

I think this happens because we raise the failure as an exception from pgexecute.run() which is caught in main.py and return just the error. 

We should probably catch the exception inside pgexecute.run() and convert it to a message and return that. 

Do you want to take that or should I?

**Comment by darikg** [comment]
Go ahead!

On Mon, Aug 17, 2015 at 12:43 PM, Amjith Ramanujam <notifications@github.com
