### ISSUE TITLE
Command run time wrong

### ISSUE THREAD

**Issue by d33tah** [dbcli/pgcli#394]
Here's output I got to a query:

```
+----------+
|    count |
|----------|
| 12353457 |
+----------+
SELECT 1
Command Time: 0.000s
Format Time: 0.002s
```

The thing is that after pressing return key, I keep waiting for a minute rather than zero seconds.

**Comment by amjith** [comment]
Yes. This is a known issue that has been fixed in master. I'll be releasing the new version soon. In the meantime you can install directly from master using the following command: 

```
pip install https://github.com/dbcli/pgcli/archive/master.zip
```

**Comment by d33tah** [comment]
`pip install -U https://github.com/dbcli/pgcli/archive/master.zip` didn't help.

**Comment by amjith** [comment]
That's surprising. Can you run:

```
select pg_sleep(2);
```

That should report ~2 seconds. Also there won't be separate `Command time` and `Format time` it is now consolidated to a single value.

**Comment by d33tah** [comment]
```
$ pgcli
Version: 0.19.2
Chat: https://gitter.im/dbcli/pgcli
Mail: https://groups.google.com/forum/#!forum/pgcli
Home: http://pgcli.com
dbname> select pg_sleep(2);
+------------+
| pg_sleep   |
|------------|
|            |
+------------+
SELECT 1
Command Time: 0.000s
Format Time: 0.000s
```

**Comment by amjith** [comment]
That's not using the pgcli from master.

I suspect that `pip` installed the latest version into a virtualenv or into a different location but the older version of pgcli still exists. So when you launch pgcli it is still launching the older version instead of the version in master. 

Can you tell me how you installed pgcli originally? You might want to try uninstalling it first.

**Comment by d33tah** [comment]
You were right. Uninstalling pgcli and installing it from master without the -U flag helped.
