### ISSUE TITLE
Humanize time display?

### ISSUE THREAD

**Issue by d33tah** [dbcli/pgcli#396]
Here's what I just noticed:

```
+----------+
|    count |
|----------|
| 12237922 |
+----------+
SELECT 1
Time: 152.868s
```

Making it `humanize.time.naturaldelta(t) + (miliseconds) + "miliseconds"` would be much more readable. What do you think about it?

**Comment by amjith** [comment]
I decided to settle on seconds as the default units because changing it between milliseconds, seconds and minutes will make it hard to compare them. 

For example, when someone runs a query and sees that it takes 1.5seconds then they optimize it somehow to make it run in 0.9s it'll be good to see 0.9 instead of 900ms. 

It adds a bit of cognitive overload to convert them between units.

So it was a conscious decision to keep it consistent. Does that answer your question?

**Comment by d33tah** [comment]
You could keep both. I once wrote a private patch for psql that adds "humanized" time information next to the milisecond count. Having a uniform unit is nice unless you're going to read how many hours the query took based on the number of seconds. I tend to run long-running queries in PostgreSQL quite often.

**Comment by j-bennet** [comment]
This was implemented and merged.
