### ISSUE TITLE
Support environment variables in .pgclirc

### ISSUE THREAD

**Issue by kristjan** [dbcli/pgcli#444]
`.psqlrc` provides a few variables like `:HOST`, `:PORT` and `:DBNAME` so you can do useful things like keep database-specific history files. Similar functionality in `.pgclirc` would be wonderful.

**Comment by amjith** [comment]
@kristjan Thanks for filing the issue. Can you give me a specific example? I haven't used this functionality in psqlrc so I'm not familiar with this feature.

**Comment by kristjan** [comment]
Absolutely, here's what the history file configuration looks like:

    \set HISTFILE ~/.psql_history_ :DBNAME

Given that, DBs `foo` and `bar` get independent query histories written to `~/.psql_history_foo` and `~/.psql_history_bar`, which looks like this:

![db_history](https://cloud.githubusercontent.com/assets/34301/12475360/5330bafc-bfd7-11e5-9e8f-7a5218bb2618.gif)

**Comment by fernandomora** [comment]
psql can set environment vars with \setenv command:
http://www.postgresql.org/docs/9.5/static/app-psql.html
> \setenv name [ value ]
> Sets the environment variable name to value, or if the value is not supplied, unsets the environment variable. Example:
> 
> test=# \setenv PAGER less
> test=# \setenv LESS -imx4F

Also you can include setting of environment vars in .psqlrc. e.g:
```
\setenv PAGER less
\setenv PAGER less
```

HISTFILE, DBNAME, PORT, etc... are not environment variables, they are internal psql variable and can be set with \set and shown with \echo :VARNAME. e.g:
```
test=# \echo :DBNAME
test
test=# \echo :ENCODING
test
```

> \set [ name [ value [ ... ] ] ]
> Sets the psql variable name to value, or if more than one value is given, to the concatenation of all of them. If only one argument is given, the variable is set with an empty value. To unset a variable, use the \unset command.

Also in .psqlrc. e.g:
```
\set VERBOSITY verbose
\set COMP_KEYWORD_CASE upper
```
I am not sure if it is easy to read/write this psql internal vars, but I'm sure it is at least for env vars. 

I purpose to allow same functionality: usage of \set (probably also \unset) and \setenv, or at least \setenv in pgcli both in command line and in .pgclirc.

Note: If this is implemented I think it would be good to make a breaking change to #452 before next release to configure default PAGER in .pgclirc using "\setenv" instead of "pager":
```
\setenv LESS '-iMSx4FXRe'
\setenv PAGER 'less'
```

This would make make .pgclirc config file much more similar to .psqlrc config file.

If you agree with this proposal, I could take a look and send a PR.
