### ISSUE TITLE
\copy filename completion

### ISSUE THREAD

**Issue by thomasballinger** [dbcli/pgcli#592]
It'd be great if `COPY <tablename> from <filename>` had filename completion! This is mentioned in #146 but that issue is closed.

I'd be happy to take a look!

**Comment by thomasballinger** [comment]
I guess the same thing applies to `\copy`

**Comment by amjith** [comment]
Please feel free to take it on. 

Here's a pointer to how we did the filename completion for the `\i` command. 

https://github.com/dbcli/pgcli/blob/master/pgcli/packages/sqlcompletion.py#L134

Returning the completion type as `Path` will use the appropriate completer which are defined here: https://github.com/dbcli/pgcli/blob/master/pgcli/pgcompleter.py#L683

**Comment by thomasballinger** [comment]
Some thoughts now that I understand this better

* This only makes sense for `\copy`, not `COPY`, unless pgcli can ask the server about paths that exist there. (unless that's something that's implemented now?)
* `\copy` allows queries in lieu of `table [ ( column_list ) ]`, but I'll ignore that for now.
* The simplest thing to do would be to just add path completion for `\copy` at all times like `\i`, but it would make sense to hook up table/column completion for before the `to`/`from` and options as well.

**Comment by amjith** [comment]
You're right. We can't do filename completion for `COPY` since that is supposed to run on the server and not on the client.

With respect to `\copy` it seems like the completion is always suggestion keywords. For example when I type `\copy SELECT * FROM ` it is not recommending tables. 

Your suggestion was to always use path file completion after the `\copy` prefix. My recommendation is, when we see `\copy` we strip out the prefix and let the completion engine take over the user input and suggest the right things based on context. 

There is precedent for this in the form of named queries. https://github.com/dbcli/pgcli/blob/master/pgcli/packages/sqlcompletion.py#L158

Named query is not a very well documented feature, but here's the summary: 

```
Named Queries are a way to save frequently used queries
with a short name. Think of them as favorites.
Examples:

    # Save a new named query.
    > \ns simple select * from abc where a is not Null;

    # List all named queries.
    > \n
    +--------+----------------------------------------+
    | Name   | Query                                  |
    |--------+----------------------------------------|
    | simple | SELECT * FROM xyzb where a is not null |
    +--------+----------------------------------------+

    # Run a named query.
    > \n simple
    +-----+
    |   a |
    |-----|
    |  50 |
    +-----+

    # Delete a named query.
    > \nd simple
    simple: Deleted

Time: 0.000s
```

But this doesn't add file path completion, that's when we enhance the completion engine to add support for path completion based on the previous keyword such as `TO`.

**Comment by thomasballinger** [comment]
Thanks so much for the guidance! This approach looks good for the case of copying a query to a file. As a reminder to myself, in addition to subqueries we'll want just table names with columns in parens.
