### ISSUE TITLE
`\h` is broken

### ISSUE THREAD

**Issue by amjith** [dbcli/pgcli#749]
## Description
Typing `\h` without any arguments returns an error: 

```
amjith@(none):world> \h
list index out of range
```

## Your environment
macOS
Installed via pip
pgcli version 1.6.0
pgspecial 1.8.0

**Comment by amjith** [comment]
@stuartquin I think you might be interested in this one. :)

**Comment by stuartquin** [comment]
Hi @amjith 

I've done some digging on this one and it seems the issue comes from way down in `cli_helpers`: https://github.com/dbcli/cli_helpers/blob/master/cli_helpers/tabular_output/preprocessors.py#L88
and
https://github.com/dbcli/cli_helpers/blob/master/cli_helpers/tabular_output/preprocessors.py#L95

I'm not familiar with this area so am hesitant to jump in and hack it but it seems adding a guard solves the issue:

```
if i < len(column_types) and column_types[i] is float and type(v) in float_types:
```

Perhaps @tsroten can suggest a cleaner solution?

Thanks

**Comment by tsroten** [comment]
@stuartquin It looks like the problem is that the data does not have even rows. The last row only has 4 items, and the rest have 6 items.

This produces two different bugs depending which pgcli version you use.
1. In pgcli < 1.7.0, you only see two-thirds of the output since the last two (out of six) columns are truncated by tabulate.
2. In pgcli 1.7.0, you get the error about the list index.

I've got a fix in CLI Helpers to make the behavior match < 1.7.0. The output looks fine if you use `ascii` as your `table_format` in pgcli. So, it looks like we'll need to address the other issue with tabulate.

**Comment by tsroten** [comment]
@stuartquin Nevermind what I said about truncating output 😄 , looks like my pager settings were messed up. I released a CLI Helpers update, so this should be fixed now.
