### ISSUE TITLE
Specifiying username: inconsistency with mycli

### ISSUE THREAD

**Issue by shtrom** [dbcli/pgcli#776]
## Description
`pgcli` takes `-U` as the option flag to specify the user; `mycli` uses `-u`. This is confusing (I had to check before writing this issue, to make sure I got them right).

Could those two be unified?

**Comment by tsroten** [comment]
@shtrom Thanks for pointing this out. This was intentional in order to make pgcli act like psql and mycli act like mysql. The idea was that users from the official client would have less of a transition to the dbcli alternative.

I'd be interested in @amjith and @j-bennet's thoughts on whether it's more important to a) make the dbcli projects provide a consistent user-experience with configs/options or b) continue to make dbcli projects act like their official counterparts.

**Comment by j-bennet** [comment]
I think it's important to make our clients behave similarly to the official clients, because people would want to use them as drop-in replacements.

**Comment by amjith** [comment]
> I think it's important to make our clients behave similarly to the official clients, because people would want to use them as drop-in replacements.

This was the original reason. My goal was to make pgcli or mycli so compelling and fully-featured that people will never have to use the official clients. It will grow to a point where they will alias `psql` and `mysql` to `pgcli` and `mycli` in their bashrc files. 

Having said that I don't see why we can't support both `-u` and `-U` for both clients. I don't see a conflict in pgcli if we use the lowercase `-u` and no conflict in mycli if we use `-U` for user. So I don't mind supporting both uppercase and lowercase `-u` for user option.

**Comment by shtrom** [comment]
That'd be awesome!

**Comment by fpietka** [comment]
@amjith although `-u` wouldn't be an issue with pgcli, `-U` would conflict with one option of mysql:
```
  -u, --user=name     User for login if not current user.
  -U, --safe-updates  Only allow UPDATE and DELETE that uses keys.
  -U, --i-am-a-dummy  Synonym for option --safe-updates, -U.
```

I must say I never used that parameter, but maybe some people has.

**Comment by amjith** [comment]
Let's stay out of using `-U` in mycli then. I think that's a useful feature that we may implement in the future.
