### ISSUE TITLE
psycopg type DateTimeTZRange exposed in TSTZRANGE results

### ISSUE THREAD

**Issue by Dowwie** [dbcli/pgcli#851]
## Description
A psycopg type  of DateTimeTZRange is exposed for a TSTZRANGE column.  This type does not exist in Postgres.   It is misleading to use it in results. 

For instance:
select tstzrange(timezone('utc', now()), timezone('utc', now())+'1 week'::interval, '[]');

## Your environment
pg10

using: pgcli v1.8.1

**Comment by dbaty** [comment]
Hi. This is an old report but I'll bite. Here is the current output (as of pgcli 4.0.1): 

```
> select tstzrange(timezone('utc', now()), timezone('utc', now())+'1 week'::interval, '[]');
```

Which output do you expect?

**Comment by Dowwie** [comment]
are you seriously asking me about an issue I reported more than 5 years ago?

**Comment by dbaty** [comment]
Hello. I was not a contributor 5 years ago when you reported this issue. But now I am. I am trying to do a bit of triage and cleaning among almost 150 open issues. It's not particularly fun to get back to reporters about issues that happened years ago. Still, I find it necessary so that _current_ contributors can focus on issues that are _still there_. Perhaps I did not word my message carefully enough given the context. I apologize if that irratated you. It obviously was not my intention.

Cheers,

Damien
