### ISSUE TITLE
Slow for wide postgis column

### ISSUE THREAD

**Issue by jtrakk** [dbcli/pgcli#976]
## Description

I have a table with a postgis wkb_geometry column, whose entries are extremely long strings of bytes (e.g. 1,000,000 hex characters). 

I'll often do `SELECT * FROM table LIMIT 1`. I'm not especially interested in reading the geometry column, but I don't mind if it's included either, so `SELECT *` is usually fine.

psql executes the above  in 2.2 milliseconds.
pgcli does the same in 0.6 seconds.
With more rows, it takes longer.

This is too slow for me. I could manually exclude the column by selecting all the columns I want, but that's fairly tedious. What options do I have for this situation? 

## Your environment

Ubuntu 18.04
Python 3.6.6
pgcli 2.0.1

**Comment by j-bennet** [comment]
Thanks for reporting it. This sounds awful!

I have no geometry data to reproduce your problem, but the same thing happens with really long text data. I timed execution time separately from formatting time, and almost all of this time is spent formatting, not retrieving data.

The problem needs to be fixed in `cli_helpers` (which is the library we use to deal with formatting). I'll see what we can do.

**Comment by amjith** [comment]
@jtrakk I wonder if you can get away with using a different table format. You can change the different table format at runtime using `\T <table_format_name>`. Once you find a format that works decent you can set that to be your default in your config file `~/.config/pgcli/config`. 

Let us know if that temporary workaround works for you.
